#!/usr/bin/env bash

if [ $# -gt 0 ]; then
  EMU=$1
  PORT=5554
  export HOME=/root
  echo "Starting emulator[$PORT]..."
  emulator -avd $EMU -no-skin -no-audio -no-window -port $PORT &
  wait-for-emulator
else
  echo "No command is specified"
fi
